//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyFlow.Presentation.Assets {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasyFlow.Presentation.Assets.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a description to Focus sessions.
        /// </summary>
        public static string AddFocusDescription {
            get {
                return ResourceManager.GetString("AddFocusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Data.
        /// </summary>
        public static string BackupData {
            get {
                return ResourceManager.GetString("BackupData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bar chart.
        /// </summary>
        public static string BarChart {
            get {
                return ResourceManager.GetString("BarChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break.
        /// </summary>
        public static string Break {
            get {
                return ResourceManager.GetString("Break", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break Alarm Sounds.
        /// </summary>
        public static string BreakAlarmSounds {
            get {
                return ResourceManager.GetString("BreakAlarmSounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break completed. Time to focus!.
        /// </summary>
        public static string BreakCompleted {
            get {
                return ResourceManager.GetString("BreakCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break time must be smaller or equal Focus time.
        /// </summary>
        public static string BreakSmallerOrEqualFocus {
            get {
                return ResourceManager.GetString("BreakSmallerOrEqualFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break time must be smaller or equal Long break time.
        /// </summary>
        public static string BreakSmallerOrEqualLongBreak {
            get {
                return ResourceManager.GetString("BreakSmallerOrEqualLongBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break Time.
        /// </summary>
        public static string BreakTime {
            get {
                return ResourceManager.GetString("BreakTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed Color Theme To.
        /// </summary>
        public static string ChangedColorTo {
            get {
                return ResourceManager.GetString("ChangedColorTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed Theme To.
        /// </summary>
        public static string ChangedThemeTo {
            get {
                return ResourceManager.GetString("ChangedThemeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete all data?.
        /// </summary>
        public static string CheckDelete {
            get {
                return ResourceManager.GetString("CheckDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose where to save.
        /// </summary>
        public static string ChooseWhereToSave {
            get {
                return ResourceManager.GetString("ChooseWhereToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls.
        /// </summary>
        public static string Controls {
            get {
                return ResourceManager.GetString("Controls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No sessions available for these controls. 
        ///
        ///Go Focus and come back later.
        /// </summary>
        public static string DashboardNoSessionAvailable {
            get {
                return ResourceManager.GetString("DashboardNoSessionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete data.
        /// </summary>
        public static string DeleteData {
            get {
                return ResourceManager.GetString("DeleteData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        public static string Display {
            get {
                return ResourceManager.GetString("Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure.
        /// </summary>
        public static string Failure {
            get {
                return ResourceManager.GetString("Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The report couldn&apos;t be generated. Try again..
        /// </summary>
        public static string FailureGeneratedReport {
            get {
                return ResourceManager.GetString("FailureGeneratedReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus.
        /// </summary>
        public static string Focus {
            get {
                return ResourceManager.GetString("Focus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus Alarm Sounds.
        /// </summary>
        public static string FocusAlarmSounds {
            get {
                return ResourceManager.GetString("FocusAlarmSounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus completed. Well done! You can rest now..
        /// </summary>
        public static string FocusCompleted {
            get {
                return ResourceManager.GetString("FocusCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus Description.
        /// </summary>
        public static string FocusDescription {
            get {
                return ResourceManager.GetString("FocusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus must be greater or equal break time.
        /// </summary>
        public static string FocusGreaterOrEqualBreak {
            get {
                return ResourceManager.GetString("FocusGreaterOrEqualBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus Time.
        /// </summary>
        public static string FocusTime {
            get {
                return ResourceManager.GetString("FocusTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long Break.
        /// </summary>
        public static string LongBreak {
            get {
                return ResourceManager.GetString("LongBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long break completed. Enough rest, time to focus!.
        /// </summary>
        public static string LongBreakCompleted {
            get {
                return ResourceManager.GetString("LongBreakCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long Break time must be greater or equal Break time.
        /// </summary>
        public static string LongBreakGreaterOrEqualBreak {
            get {
                return ResourceManager.GetString("LongBreakGreaterOrEqualBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long Break Time.
        /// </summary>
        public static string LongBreakTime {
            get {
                return ResourceManager.GetString("LongBreakTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string MenuLanguages {
            get {
                return ResourceManager.GetString("MenuLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch To....
        /// </summary>
        public static string MenuSwitchTo {
            get {
                return ResourceManager.GetString("MenuSwitchTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Themes.
        /// </summary>
        public static string MenuThemes {
            get {
                return ResourceManager.GetString("MenuThemes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Past 30 days.
        /// </summary>
        public static string Past30Days {
            get {
                return ResourceManager.GetString("Past30Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Past 48 hours.
        /// </summary>
        public static string Past48Hours {
            get {
                return ResourceManager.GetString("Past48Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Past 5 years.
        /// </summary>
        public static string Past5Years {
            get {
                return ResourceManager.GetString("Past5Years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Past 7 days.
        /// </summary>
        public static string Past7Days {
            get {
                return ResourceManager.GetString("Past7Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Past 90 days.
        /// </summary>
        public static string Past90Days {
            get {
                return ResourceManager.GetString("Past90Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Past year.
        /// </summary>
        public static string PastYear {
            get {
                return ResourceManager.GetString("PastYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play alarm sounds after break sessions.
        /// </summary>
        public static string PlaySoundsAfterBreak {
            get {
                return ResourceManager.GetString("PlaySoundsAfterBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play alarm sounds after Focus sessions.
        /// </summary>
        public static string PlaySoundsAfterFocus {
            get {
                return ResourceManager.GetString("PlaySoundsAfterFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese.
        /// </summary>
        public static string Portuguese {
            get {
                return ResourceManager.GetString("Portuguese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date,Duration (Minutes),Tag,Session Type.
        /// </summary>
        public static string ReportColumns {
            get {
                return ResourceManager.GetString("ReportColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restarting....
        /// </summary>
        public static string Restarting {
            get {
                return ResourceManager.GetString("Restarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sessions.
        /// </summary>
        public static string Sessions {
            get {
                return ResourceManager.GetString("Sessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sessions before long time break.
        /// </summary>
        public static string SessionsBeforeLongBreak {
            get {
                return ResourceManager.GetString("SessionsBeforeLongBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sessions (Minutes).
        /// </summary>
        public static string SessionsMinutes {
            get {
                return ResourceManager.GetString("SessionsMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Type.
        /// </summary>
        public static string SessionType {
            get {
                return ResourceManager.GetString("SessionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It will show in the report..
        /// </summary>
        public static string ShowInTheReport {
            get {
                return ResourceManager.GetString("ShowInTheReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string SideMenuDashboard {
            get {
                return ResourceManager.GetString("SideMenuDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus.
        /// </summary>
        public static string SideMenuFocus {
            get {
                return ResourceManager.GetString("SideMenuFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SideMenuSettings {
            get {
                return ResourceManager.GetString("SideMenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip to Break.
        /// </summary>
        public static string SkipToBreak {
            get {
                return ResourceManager.GetString("SkipToBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip to Focus.
        /// </summary>
        public static string SkipToFocus {
            get {
                return ResourceManager.GetString("SkipToFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound Volume.
        /// </summary>
        public static string SoundVolume {
            get {
                return ResourceManager.GetString("SoundVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup saved successfully.
        /// </summary>
        public static string SuccessGeneratedBackup {
            get {
                return ResourceManager.GetString("SuccessGeneratedBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The report was successfully generated.
        /// </summary>
        public static string SuccessGeneratedReport {
            get {
                return ResourceManager.GetString("SuccessGeneratedReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound volume is set to.
        /// </summary>
        public static string VolumeSound {
            get {
                return ResourceManager.GetString("VolumeSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggestions
        ///
        ///What did you focus on?
        ///
        ///What did you complete?
        ///
        ///What were the challenges?.
        /// </summary>
        public static string WatermarkDescriptionSuggestion {
            get {
                return ResourceManager.GetString("WatermarkDescriptionSuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write your notes about the last session..
        /// </summary>
        public static string WriteNotes {
            get {
                return ResourceManager.GetString("WriteNotes", resourceCulture);
            }
        }
    }
}
