name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: Restore dependencies
      run: dotnet restore src/
    
    - name: Build
      run: dotnet build src/ --no-restore

    - name: Run unit tests
      run: dotnet test src/EasyFlow.Tests.Unit/ --no-restore --verbosity normal