name: Publish

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Platform to publish'
        required: true
        default: 'all'
        type: choice
        options:
          - 'windows'
          - 'linux'
          - 'android'
          - 'all'

env:
  DOTNET_VERSION: '9.x'
  PRESENTATION_PATH: src/client/presentation

jobs:
  publish-windows:
    if: ${{ github.event.inputs.platform == 'windows' || github.event.inputs.platform == 'all' }}
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Make upload directory
        run: mkdir upload

      - name: Publish win-x64
        run: dotnet publish $PRESENTATION_PATH/EasyFocus.Windows -r win-x64 -c Release --sc /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true -o ./publish/win64

      - name: Zip win-x64
        run: |
          $files = Get-ChildItem -Path ./publish/win64/* -Recurse -Exclude *.pdb
          Compress-Archive -Path $files.FullName -DestinationPath ./upload/EasyFocus.win-x64.zip

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: windows
          path: ./upload

  publish-linux:
    if: ${{ github.event.inputs.platform == 'linux' || github.event.inputs.platform == 'all' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Make upload directory
        run: mkdir upload

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
        
      - name: Publish linux-x64
        run: dotnet publish $PRESENTATION_PATH/EasyFocus.Linux -r linux-x64 -c Release --sc /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true -o ./publish/linux64
      
      - name: Zip linux-x64
        run: zip -j -r ./upload/EasyFocus.linux-x64.zip ./publish/linux64 -x "*.pdb"

      - name: Publish linux-arm64
        run: dotnet publish $PRESENTATION_PATH/EasyFocus.Linux -c Release -o ./publish/linuxarm64 -r linux-arm64 -p:PublishReadyToRun=true -p:PublishSingleFile=true -p:PublishTrimmed=true --self-contained true -p:IncludeNativeLibrariesForSelfExtract=true

      - name: Zip linux-arm64
        run: zip -j -r ./upload/EasyFocus.linux-arm64.zip ./publish/linuxarm64 -x "*.pdb"

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: linux
          path: ./upload

  publish-android:
    if: ${{ github.event.inputs.platform == 'android' || github.event.inputs.platform == 'all' }}
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore $PRESENTATION_PATH/EasyFocus.Android
     
      - name: Publish Android
        run: dotnet publish $PRESENTATION_PATH/EasyFocus.Android -c Release -f net9.0-android --no-restore -o ./publish -p:RuntimeIdentifier=android-arm64

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: android
          path: ./publish/*Signed.apk